/**
 * Tests for renderFullPlanArchetypeMarkdown (W1-F2 port).
 *
 * Mirrors the in-host `src/agents/plan-render.test.ts` "PR-14"
 * describe block (the slice we ported). The full multi-format
 * `renderPlanChecklist` matrix is in-host-only — the plugin port
 * only ships the markdown branch used by the persister.
 */

import { describe, expect, it } from "vitest";
import { renderFullPlanArchetypeMarkdown } from "../../src/plan-mode/plan-render.js";

describe("renderFullPlanArchetypeMarkdown — host parity", () => {
  const FIXED_DATE = new Date("2026-04-18T15:30:00Z");

  it("emits title heading + plan checklist for a minimal input", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Hello",
      plan: [{ step: "do thing", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    expect(out).toContain("# Hello");
    expect(out).toContain("## Plan");
    expect(out).toContain("- [ ] do thing");
    // Footer always rendered.
    expect(out).toContain(
      "_Generated by OpenClaw on 2026-04-18. Resolve with",
    );
  });

  it("renders all archetype sections when provided", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Bump deps",
      summary: "Update tooling",
      analysis: "Current state\n\nNew approach",
      plan: [
        { step: "bump eslint", status: "completed" },
        { step: "bump prettier", status: "in_progress" },
        { step: "bump vitest", status: "pending" },
        { step: "old", status: "cancelled" },
      ],
      assumptions: ["nodejs is at v20"],
      risks: [{ risk: "tests may flake", mitigation: "retry the suite" }],
      verification: ["pnpm test passes"],
      references: ["src/x.ts:1", "PR #99"],
      generatedAt: FIXED_DATE,
    });
    // Sections in canonical order.
    const order = [
      "## Summary",
      "## Analysis",
      "## Plan",
      "## Assumptions",
      "## Risks",
      "## Verification",
      "## References",
    ];
    let prevIdx = -1;
    for (const section of order) {
      const idx = out.indexOf(section);
      expect(idx).toBeGreaterThan(prevIdx);
      prevIdx = idx;
    }
    // Step rendering covers all four status markers.
    expect(out).toContain("- [x] bump eslint");
    expect(out).toContain("- [>] **bump prettier**");
    expect(out).toContain("- [ ] bump vitest");
    expect(out).toContain("- [~] ~~old~~");
    // Risks shape: `- **<risk>**: <mitigation>`. (Escapes the colon
    // depending on context; not the `:` separator in this template.)
    expect(out).toMatch(/- \*\*tests may flake\*\*: retry the suite/);
  });

  it("omits optional sections when fields are absent/empty", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "T",
      plan: [{ step: "a", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    expect(out).not.toContain("## Summary");
    expect(out).not.toContain("## Analysis");
    expect(out).not.toContain("## Assumptions");
    expect(out).not.toContain("## Risks");
    expect(out).not.toContain("## Verification");
    expect(out).not.toContain("## References");
  });

  it("renders empty plan as `_No plan steps provided._`", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Hollow",
      plan: [],
      generatedAt: FIXED_DATE,
    });
    expect(out).toContain("## Plan");
    expect(out).toContain("_No plan steps provided._");
  });

  it("escapes markdown meta-characters in title", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Title with [brackets](evil) and *bold*",
      plan: [{ step: "x", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    expect(out).toContain(
      "# Title with \\[brackets\\]\\(evil\\) and \\*bold\\*",
    );
  });

  it("neutralizes @mentions in step text (Discord/Mattermost protection)", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Plan",
      plan: [{ step: "@everyone deploy now", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    // Real @everyone is broken by inserting U+FE6B after the @.
    expect(out).not.toMatch(/^- \[ \] @everyone deploy now/m);
    expect(out).toContain("@﹫everyone");
  });

  it("neutralizes Discord raw-mention <@123> via zero-width insert", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Plan",
      plan: [{ step: "ping <@123456>", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    // <@ becomes <U+200B@
    expect(out).toContain("<​@");
  });

  it("uses activeForm in_progress label when present", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Plan",
      plan: [
        {
          step: "Run the test suite",
          status: "in_progress",
          activeForm: "Running tests",
        },
      ],
      generatedAt: FIXED_DATE,
    });
    expect(out).toContain("- [>] **Running tests**");
  });

  it("falls back to step text when activeForm is whitespace-only", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Plan",
      plan: [
        {
          step: "Build it",
          status: "in_progress",
          activeForm: "   ",
        },
      ],
      generatedAt: FIXED_DATE,
    });
    expect(out).toContain("- [>] **Build it**");
  });

  it("strips embedded newlines from step text", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "Plan",
      plan: [{ step: "line1\nline2", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    // Single bullet, joined with a space.
    expect(out).toContain("- [ ] line1 line2");
    expect(out).not.toContain("- [ ] line1\nline2");
  });

  it("filters blank entries from assumptions/verification/references arrays", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "T",
      plan: [{ step: "a", status: "pending" }],
      assumptions: ["", "  ", "real assumption", "   "],
      verification: ["", "real verify"],
      references: ["real ref", ""],
      generatedAt: FIXED_DATE,
    });
    // Sections render.
    expect(out).toContain("## Assumptions");
    expect(out).toContain("- real assumption");
    expect(out).toContain("- real verify");
    expect(out).toContain("- real ref");
    // Blank entries are NOT rendered as empty bullets.
    expect(out).not.toMatch(/- $/m);
  });

  it("drops the risks section when no entry has both risk + mitigation", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "T",
      plan: [{ step: "a", status: "pending" }],
      risks: [
        { risk: "", mitigation: "x" },
        { risk: "y", mitigation: "" },
      ],
      generatedAt: FIXED_DATE,
    });
    expect(out).not.toContain("## Risks");
  });

  it("falls back to 'Untitled plan' for empty title", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "",
      plan: [{ step: "a", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    expect(out).toContain("# Untitled plan");
  });

  it("ends with a trailing newline (for clean disk write)", () => {
    const out = renderFullPlanArchetypeMarkdown({
      title: "T",
      plan: [{ step: "a", status: "pending" }],
      generatedAt: FIXED_DATE,
    });
    expect(out.endsWith("\n")).toBe(true);
  });
});
